------------------------------------ SPs para CRUD de HOTEL_TAB

----INSERT
create or replace PROCEDURE SP_INSERT_HOTEL(
ID_DIRECCION_V NUMBER,
ID_HORARIO_V NUMBER,
NOMBRE_V NVARCHAR2,
TELEFONO_V NVARCHAR2,
CORREO_V NVARCHAR2
)
is 
begin

    INSERT INTO HOTEL_TB(ID_DIRECCION ,ID_HORARIO ,NOMBRE ,TELEFONO ,CORREO )
    VALUES (ID_DIRECCION_V ,ID_HORARIO_V ,NOMBRE_V ,TELEFONO_V ,CORREO_V);
    COMMIT;
end;
/
--EXECUTE SP_INSERT_HOTEL(1,1,1, 'NOMBRE', '123456789', 'NOMBRE@ejemplo.com');


----UPDATE
create or replace PROCEDURE SP_UPDATE_HOTEL(
ID_HOTEL_V NUMBER,
ID_DIRECCION_V NUMBER,
ID_HORARIO_V NUMBER,
NOMBRE_V NVARCHAR2,
TELEFONO_V NVARCHAR2,
CORREO_V NVARCHAR2
)
is 
begin
    UPDATE HOTEL_TB SET
    ID_DIRECCION  = ID_DIRECCION_V,
    ID_HORARIO = ID_HORARIO_V,
    NOMBRE = NOMBRE_V,
    TELEFONO = TELEFONO_V,
    CORREO = CORREO_V
    WHERE ID_HOTEL = ID_HOTEL_V;
    COMMIT;
end;

/
--EXECUTE SP_UPDATE_HOTEL(1,1,1, 'NOMBRE_UPD', '123456789', 'UPDATE@ejemplo.com');


----DELETE
create or replace PROCEDURE SP_DELETE_HOTEL(
ID_HOTEL_V NUMBER
)
is 
begin

    DELETE FROM HOTEL_TB
    WHERE ID_HOTEL = ID_HOTEL_V;
    
    COMMIT;
end;

--EXECUTE SP_DELETE_HOTEL(1);
/

------------------------------------ SPs para CRUD de DIRECCION_TB

----INSERT
create or replace PROCEDURE SP_INSERT_DIRECCION(
PROVINCIA_V NVARCHAR2,
CANTON_V NVARCHAR2,
DISTRITO_V NVARCHAR2,
DIRECCION_DETALLADA_V NVARCHAR2
)
is 
begin

    INSERT INTO DIRECCION_TB(PROVINCIA ,CANTON ,DISTRITO ,DIRECCION_DETALLADA )
    VALUES (PROVINCIA_V ,CANTON_V ,DISTRITO_V ,DIRECCION_DETALLADA_V);
    COMMIT;
end;
/
--EXECUTE SP_INSERT_DIRECCION('HEREDIA', 'SANTA BARBARA', 'SANTA BARBARA', 'DETRAS DE LA PARROQUIA 100 SUR');


----UPDATE
create or replace PROCEDURE SP_UPDATE_DIRECCION(
ID_DIRECCION_V NUMBER,
PROVINCIA_V NVARCHAR2,
CANTON_V NVARCHAR2,
DISTRITO_V NVARCHAR2,
DIRECCION_DETALLADA_V NVARCHAR2
)
is 
begin
    UPDATE DIRECCION_TB SET
    PROVINCIA = PROVINCIA_V,
    CANTON = CANTON_V,
    DISTRITO = DISTRITO_V,
    DIRECCION_DETALLADA = DIRECCION_DETALLADA_V
    WHERE ID_DIRECCION = ID_DIRECCION_V;
    COMMIT;
end;

/
--EXECUTE SP_UPDATE_DIRECCION('HEREDIA', 'SANTA BARBARA', 'SAN PEDRO', '500 NORTE DEL PARQUE');


----DELETE
create or replace PROCEDURE SP_DELETE_DIRECCION(
ID_DIRECCION_V NUMBER
)
is 
begin

    DELETE FROM DIRECCION_TB
    WHERE ID_DIRECCION = ID_DIRECCION_V;
    
    COMMIT;
end;

--EXECUTE SP_DELETE_DIRECCION(1);

/
------------------------------------ SPs para CRUD de SERVICIO_HOTEL_TAB

----INSERT
create or replace PROCEDURE SP_INSERT_SERVICIO_HOTEL(
ID_HOTEL_V NUMBER,
NOMBRE_V NVARCHAR2,
ESTADO_V NVARCHAR2
)
is 
begin

    INSERT INTO SERVICIO_HOTEL_TAB(ID_HOTEL ,NOMBRE ,ESTADO )
    VALUES (ID_HOTEL_V ,NOMBRE_V ,ESTADO_V);
    COMMIT;
end;
/
--EXECUTE SP_INSERT_SERVICIO_HOTEL(1, 'SERVICIO', 'ACTIVO');


----UPDATE
create or replace PROCEDURE SP_UPDATE_SERVICIO_HOTEL(
ID_SERVICIO_HOTEL_V NUMBER,
NOMBRE_V NVARCHAR2,
ESTADO_V NVARCHAR2
)
is 
begin
    UPDATE SERVICIO_HOTEL_TAB SET
    NOMBRE = NOMBRE_V,
    ESTADO = ESTADO_V
    WHERE ID_SERVICIO_HOTEL = ID_SERVICIO_HOTEL_V;
    COMMIT;
end;

/
--EXECUTE SP_UPDATE_SERVICIO_HOTEL(1, 'SERVICIO', 'INACTIVO');


----DELETE
create or replace PROCEDURE SP_DELETE_SERVICIO_HOTEL(
ID_SERVICIO_HOTEL_V NUMBER
)
is 
begin

    DELETE FROM SERVICIO_HOTEL_TAB
    WHERE ID_SERVICIO_HOTEL = ID_SERVICIO_HOTEL_V;
    
    COMMIT;
end;

--EXECUTE SP_DELETE_SERVICIO_HOTEL(1);
/


create or replace PROCEDURE OBTENER_HORARIOS(
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    -- Abrir el cursor y seleccionar todos los registros de la tabla SERVICIO_TB
    OPEN P_CURSOR FOR
    SELECT ID_HORARIO, FECHA_HORARIO, HORA_APERTURA, HORA_CIERRE
    FROM HORARIO_TB;
END;

INSERT INTO DIRECCION_TB (ID_DIRECCION, PROVINCIA, CANTON, DISTRITO, DIRECCION_DETALLADA) VALUES (1, 'San José', 'Escazú', 'San Rafael', 'Centro Comercial Multiplaza');
INSERT INTO DIRECCION_TB (ID_DIRECCION, PROVINCIA, CANTON, DISTRITO, DIRECCION_DETALLADA) VALUES (2, 'Heredia', 'Belén', 'Asunción', 'Zona Franca América, Edificio 5');

--

--EXECUTE SP_DELETE_HOTEL(1);
/
CREATE OR REPLACE PROCEDURE OBTENER_HOTEL(
    RESULTADO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN RESULTADO FOR
    SELECT ID_HOTEL,d.direccion_detallada,hr.fecha_horario,NOMBRE, TELEFONO, CORREO
    FROM HOTEL_TB h inner join direccion_tb d
    on h.id_direccion = d.id_direccion
    inner join horario_tb hr
    on h.id_horario = hr.id_horario;
END;
/

--
create or replace PROCEDURE OBTENER_HORARIO_POR_ID(
    P_ID_HORARIO IN HORARIO_TB.ID_HORARIO%TYPE, -- ID del horario que se desea consultar
    RESULTADO OUT SYS_REFCURSOR                 -- Cursor para devolver el resultado
)
AS
BEGIN
    -- Abrir un cursor con la consulta SELECT filtrada por ID_HORARIO
    OPEN RESULTADO FOR
    SELECT ID_HORARIO, FECHA_HORARIO, HORA_APERTURA, HORA_CIERRE
    FROM HORARIO_TB
    WHERE ID_HORARIO = P_ID_HORARIO;
END;
--

create or replace PROCEDURE OBTENER_DIRECCIONES(
    RESULTADO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN RESULTADO FOR
    SELECT ID_DIRECCION,PROVINCIA, CANTON, DISTRITO,DIRECCION_DETALLADA
    FROM DIRECCION_TB;
END;

--
create or replace PROCEDURE OBTENER_DIRECCION_POR_ID(
    P_ID_DIRECCION IN DIRECCION_TB.ID_DIRECCION%TYPE, 
    RESULTADO OUT SYS_REFCURSOR        
)
AS
BEGIN
    OPEN RESULTADO FOR
    SELECT ID_DIRECCION,PROVINCIA, CANTON, DISTRITO,DIRECCION_DETALLADA
    FROM DIRECCION_TB
    WHERE ID_DIRECCION = P_ID_DIRECCION;
END;
---


    
    
    
    
    
    
